// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RollupTaskRunner
{
    static class Vsix
    {
        public const string Id = "356dbaea-0513-4de0-8343-822a753e771b";
        public const string Name = "Rollup Task Runner";
        public const string Description = @"Task Runner Explorer support for Rollup.js - The next generation JavaScript module bundler.";
        public const string Language = "en-US";
        public const string Version = "1.1.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "rollup, task runner, javascript, bundler";
    }
}
